// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWoGUYQ0Uo3nELIeOJMKqXEUfLSdG61s',
    appId: '1:954880033258:android:9b322a0b54397238ae3293',
    messagingSenderId: '954880033258',
    projectId: 'smartclasscheckin',
    storageBucket: 'smartclasscheckin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIE6g0L9YlVE3DOcMH3E_L8MwD3OAm5Sc',
    appId: '1:954880033258:ios:04d5fbdccfd6cfc0ae3293',
    messagingSenderId: '954880033258',
    projectId: 'smartclasscheckin',
    storageBucket: 'smartclasscheckin.firebasestorage.app',
    iosBundleId: 'com.university.smartCheckinApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWYw-pG-5DZRrtPkkA5JXfnc2pDliOo0',
    appId: '1:954880033258:web:3aea368358c586c3ae3293',
    messagingSenderId: '954880033258',
    projectId: 'smartclasscheckin',
    authDomain: 'smartclasscheckin.firebaseapp.com',
    storageBucket: 'smartclasscheckin.firebasestorage.app',
    measurementId: 'G-5K6LZRY2N5',
  );

}